import { Router } from 'express';
import { z } from 'zod';
import { type DB, one, all, transaction } from '../db.js';
import { id, now, check, permit, shipmentFor, scope, event, audit, notify, pageParams, activeStatuses, setting } from '../core.js';
import { bookingSchema, transitions, statuses, type Booking, type Quote, type Rate, type Shipment, type User, type Vehicle } from '../../../../packages/shared/src/index.js';
export function distanceKm(a: number, b: number, c: number, d: number) { const rad = (x: number) => x * Math.PI / 180; const h = Math.sin(rad(c - a) / 2) ** 2 + Math.cos(rad(a)) * Math.cos(rad(c)) * Math.sin(rad(d - b) / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(Math.max(0, 1 - h))); }
export function quote(db: DB, v: Booking): Quote { const r = one<Rate>(db, 'SELECT * FROM rates WHERE service=?', v.service)!; const distance = Math.max(1, Math.round(distanceKm(v.pickup.lat, v.pickup.lng, v.delivery.lat, v.delivery.lng) * 10) / 10); check(v.service !== 'SAME_DAY' || distance <= 150, 'Same-day service is limited to 150 km straight-line distance'); const billableWeight = Math.max(v.weight, v.length * v.width * v.height / 5000); const base = Math.round(r.base * r.multiplier), distanceFee = Math.round(distance * r.per_km * r.multiplier), weightFee = Math.round(billableWeight * r.per_kg * r.multiplier), insurance = Math.round(v.declaredValue * .01); return { amount: base + distanceFee + weightFee + insurance, distance, billableWeight, base, distanceFee, weightFee, insurance, slaHours: r.sla_hours, currency: setting(db, 'currency') }; }
export function createShipment(db: DB, v: Booking, actor: User) { const customerId = actor.role === 'CUSTOMER' ? actor.id : v.customerId; check(customerId, 'Select a customer'); check(one(db, "SELECT id FROM users WHERE id=? AND role='CUSTOMER' AND active=1", customerId), 'Active customer required'); check(new Date(v.pickupAt).getTime() >= Date.now() - 3600000, 'Pickup time must not be in the past'); const q = quote(db, v); const shipmentId = id(), tracking = 'ATL-' + id().replaceAll('-', '').slice(0, 16).toUpperCase(), created = now(); return transaction(db, () => { const values = { id: shipmentId, tracking, customer_id: customerId, recipient_name: v.recipientName, recipient_phone: v.recipientPhone, pickup_address: v.pickup.address, pickup_city: v.pickup.city, pickup_lat: v.pickup.lat, pickup_lng: v.pickup.lng, delivery_address: v.delivery.address, delivery_city: v.delivery.city, delivery_lat: v.delivery.lat, delivery_lng: v.delivery.lng, weight: v.weight, length: v.length, width: v.width, height: v.height, declared_value: v.declaredValue, service: v.service, status: 'BOOKED', price: q.amount, distance: q.distance, quote_json: JSON.stringify(q), notes: v.notes, pickup_at: v.pickupAt, due_at: new Date(new Date(v.pickupAt).getTime() + q.slaHours * 3600000).toISOString(), created_at: created, updated_at: created }; db.prepare(`INSERT INTO shipments(${Object.keys(values).join(',')}) VALUES(${Object.keys(values).map(() => '?').join(',')})`).run(...Object.values(values)); const invoiceId = id(); db.prepare('INSERT INTO invoices VALUES(?,?,?,?,?,?,?)').run(invoiceId, 'INV-' + tracking.slice(4), shipmentId, customerId, q.amount, 'OPEN', created); const s = one<Shipment>(db, 'SELECT * FROM shipments WHERE id=?', shipmentId)!; event(db, s, 'BOOKED', 'Shipment booked', actor.id); audit(db, actor.id, 'CREATE', 'shipment', shipmentId); return s; }); }
export function assignShipment(db: DB, s: Shipment, driverId: string, vehicleId: string, actor: User) { check(['BOOKED', 'ASSIGNED', 'FAILED'].includes(s.status), 'Cannot assign a shipment already in transit'); const openRoute = one<{
    driver_id: string;
    vehicle_id: string;
}>(db, "SELECT r.driver_id,r.vehicle_id FROM stops st JOIN routes r ON r.id=st.route_id WHERE st.shipment_id=? AND r.status!='COMPLETED'", s.id); check(!openRoute || (openRoute.driver_id === driverId && openRoute.vehicle_id === vehicleId), 'An open route locks the assigned driver and vehicle'); check(one(db, "SELECT id FROM users WHERE id=? AND role='DRIVER' AND active=1", driverId), 'Active driver required'); const vehicle = one<Vehicle>(db, "SELECT * FROM vehicles WHERE id=? AND status='AVAILABLE'", vehicleId); check(vehicle, 'Available vehicle required'); check(!one(db, `SELECT id FROM shipments WHERE id!=? AND status IN ${activeStatuses} AND ((vehicle_id=? AND driver_id!=?) OR (driver_id=? AND vehicle_id!=?))`, s.id, vehicleId, driverId, driverId, vehicleId), 'Driver or vehicle already assigned to incompatible active jobs'); const load = one<{
    total: number;
}>(db, `SELECT COALESCE(SUM(weight),0) total FROM shipments WHERE vehicle_id=? AND id!=? AND status IN ${activeStatuses}`, vehicleId, s.id)!.total; check(load + s.weight <= vehicle.capacity, 'Vehicle capacity exceeded'); db.prepare("UPDATE shipments SET driver_id=?,vehicle_id=?,status='ASSIGNED',updated_at=?,version=version+1 WHERE id=?").run(driverId, vehicleId, now(), s.id); event(db, s, 'ASSIGNED', 'Driver assigned', actor.id); notify(db, driverId, 'Delivery assigned', s.tracking, `/shipments/${s.id}`); audit(db, actor.id, 'ASSIGN', 'shipment', s.id, JSON.stringify({ driverId, vehicleId })); }
export function shipmentRoutes(db: DB) {
    const r = Router();
    r.post('/quote', permit('ADMIN', 'DISPATCHER', 'CUSTOMER'), (req, res) => res.json(quote(db, bookingSchema.parse(req.body))));
    r.get('/', (req, res) => { const { page, limit } = pageParams(req); const sc = scope(req.user); const where = [sc.sql], args: (string | number)[] = [...sc.args]; if (req.query.status) {
        where.push('s.status=?');
        args.push(z.enum(statuses).parse(req.query.status));
    } if (req.query.search) {
        where.push('(s.tracking LIKE ? OR s.recipient_name LIKE ? OR s.delivery_city LIKE ?)');
        const search = '%' + String(req.query.search).slice(0, 100) + '%';
        args.push(search, search, search);
    } const sql = where.join(' AND '); res.json({ items: all(db, `SELECT s.*,u.name customer_name,d.name driver_name,v.plate FROM shipments s JOIN users u ON u.id=s.customer_id LEFT JOIN users d ON d.id=s.driver_id LEFT JOIN vehicles v ON v.id=s.vehicle_id WHERE ${sql} ORDER BY s.created_at DESC LIMIT ? OFFSET ?`, ...args, limit, (page - 1) * limit), total: one<{
            n: number;
        }>(db, `SELECT COUNT(*) n FROM shipments s WHERE ${sql}`, ...args)!.n, page, limit }); });
    r.post('/', permit('ADMIN', 'DISPATCHER', 'CUSTOMER'), (req, res) => res.status(201).json(createShipment(db, bookingSchema.parse(req.body), req.user)));
    r.get('/:id', (req, res) => { const s = shipmentFor(db, req.user, String(req.params.id)); res.json({ shipment: s, events: all(db, 'SELECT e.*,u.name actor_name FROM events e LEFT JOIN users u ON u.id=e.actor_id WHERE shipment_id=? ORDER BY e.created_at', s.id), location: one(db, 'SELECT lat,lng,accuracy,created_at FROM locations WHERE shipment_id=? ORDER BY created_at DESC LIMIT 1', s.id) ?? null, custody: one(db, 'SELECT h.name,c.received_at FROM custody c JOIN hubs h ON h.id=c.hub_id WHERE c.shipment_id=?', s.id) ?? null, quote: JSON.parse((s as Shipment & {
            quote_json: string;
        }).quote_json) }); });
    r.post('/:id/assign', permit('ADMIN', 'DISPATCHER'), (req, res) => { const v = z.object({ driverId: z.string(), vehicleId: z.string(), version: z.number().int() }).parse(req.body); transaction(db, () => { const s = shipmentFor(db, req.user, String(req.params.id)); check(s.version === v.version, 'Shipment changed. Refresh and try again.', 409); assignShipment(db, s, v.driverId, v.vehicleId, req.user); }); res.json({ ok: true }); });
    r.post('/:id/status', permit('ADMIN', 'DISPATCHER', 'DRIVER', 'CUSTOMER'), (req, res) => { const v = z.object({ status: z.enum(statuses), note: z.string().max(1000).default(''), recipientName: z.string().max(100).optional(), version: z.number().int() }).parse(req.body); transaction(db, () => { const s = shipmentFor(db, req.user, String(req.params.id)); check(s.version === v.version, 'Shipment changed. Refresh and try again.', 409); check(transitions[s.status].includes(v.status), 'Invalid status transition', 409); if (req.user.role === 'CUSTOMER')
        check(s.status === 'BOOKED' && v.status === 'CANCELLED', 'Customers can only cancel unassigned bookings', 403); if (req.user.role === 'DRIVER')
        check(!['CANCELLED', 'ASSIGNED'].includes(v.status), 'Dispatch must authorize this action', 403); check(v.status !== 'ASSIGNED', 'Use dispatch assignment to retry a failed delivery'); if (['OUT_FOR_DELIVERY', 'DELIVERED', 'RETURNED', 'CANCELLED'].includes(v.status))
        check(!one(db, 'SELECT shipment_id FROM custody WHERE shipment_id=?', s.id), 'Depart the shipment from its hub first'); if (['FAILED', 'RETURNED', 'CANCELLED'].includes(v.status))
        check(v.note.trim().length >= 5, 'Provide a reason of at least 5 characters'); if (v.status === 'DELIVERED')
        check((v.recipientName?.trim().length ?? 0) >= 2, 'Recipient name is required for delivery proof'); if (v.status === 'CANCELLED') {
        check(!one(db, 'SELECT p.id FROM payments p JOIN invoices i ON i.id=p.invoice_id WHERE i.shipment_id=?', s.id), 'Paid bookings need finance review; cancellation is blocked');
        db.prepare("UPDATE invoices SET status='VOID' WHERE shipment_id=?").run(s.id);
    } db.prepare('UPDATE shipments SET status=?,updated_at=?,version=version+1,proof_name=?,proof_note=?,delivered_at=? WHERE id=?').run(v.status, now(), v.status === 'DELIVERED' ? v.recipientName! : null, v.status === 'DELIVERED' ? v.note : null, v.status === 'DELIVERED' ? now() : null, s.id); event(db, s, v.status, v.note || v.status.replaceAll('_', ' '), req.user.id); audit(db, req.user.id, 'STATUS', 'shipment', s.id, JSON.stringify({ from: s.status, to: v.status })); }); res.json({ ok: true }); });
    r.post('/:id/location', permit('DRIVER'), (req, res) => { const v = z.object({ lat: z.number().min(-90).max(90), lng: z.number().min(-180).max(180), accuracy: z.number().min(0).max(100000) }).parse(req.body); const s = shipmentFor(db, req.user, String(req.params.id)); check(['PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY'].includes(s.status), 'Location updates require an active delivery'); db.prepare('INSERT INTO locations VALUES(?,?,?,?,?,?,?)').run(id(), s.id, req.user.id, v.lat, v.lng, v.accuracy, now()); res.json({ ok: true }); });
    return r;
}
