import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Printer } from 'lucide-react';
import { roles, money, type User, type Vehicle, type Hub, type Shipment } from '@atlas/shared';
import { useApp, useData, PageTitle, Panel, Form, Action, ErrorBox, Loading, Empty, Badge, post, patch, options, date, type Field } from '../lib';
export function Fleet() { const { data, error } = useData<(Vehicle & {
    load: number;
})[]>('/fleet'), { reload, toast } = useApp(); const [edit, setEdit] = useState<Vehicle | null | undefined>(undefined), [maintenance, setMaintenance] = useState<string | null>(null); const { data: history } = useData<{
    id: string;
    description: string;
    cost: number;
    performed_at: string;
    odometer: number;
}[]>(maintenance ? `/fleet/${maintenance}/maintenance` : null); const fields: Field[] = [{ name: 'plate', label: 'Registration plate', value: edit?.plate }, { name: 'model', label: 'Make / model', value: edit?.model }, { name: 'capacity', label: 'Capacity (kg)', type: 'number', min: 1, value: edit?.capacity }, { name: 'status', label: 'Availability', type: 'select', options: options(['AVAILABLE', 'MAINTENANCE', 'INACTIVE']), value: edit?.status || 'AVAILABLE' }, { name: 'odometer', label: 'Odometer (km)', type: 'number', min: 0, value: edit?.odometer ?? 0 }, { name: 'serviceDue', label: 'Next service due', type: 'date', value: edit?.service_due }]; return <><PageTitle title="Fleet management" subtitle="Vehicle availability, load capacity, and maintenance history." action={<button className="primary" onClick={() => setEdit(null)}><Plus size={16}/> Add vehicle</button>}/><ErrorBox message={error}/>{edit !== undefined && <Panel title={edit ? 'Edit vehicle' : 'New vehicle'} action={<button onClick={() => setEdit(undefined)}>Close</button>}><Form key={edit?.id || 'new'} fields={fields} submit="Save vehicle" onSubmit={async (v) => { const body = { ...v, capacity: Number(v.capacity), odometer: Number(v.odometer) }; if (edit)
    await patch('/fleet/' + edit.id, body);
else
    await post('/fleet', body); setEdit(undefined); reload(); toast('Vehicle saved'); }}/></Panel>}<Panel><div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Status</th><th>Assigned load</th><th>Odometer</th><th>Service due</th><th>Actions</th></tr></thead><tbody>{data?.map(v => <tr key={v.id}><td><strong>{v.plate}</strong><small>{v.model}</small></td><td><Badge value={v.status}/></td><td>{v.load} / {v.capacity} kg<div className="mini-progress"><span style={{ width: Math.min(100, v.load / v.capacity * 100) + '%' }}/></div></td><td>{v.odometer.toLocaleString()} km</td><td>{v.service_due}</td><td><div className="button-row"><button onClick={() => setEdit(v)}>Edit</button><button onClick={() => setMaintenance(v.id)}>Service log</button></div></td></tr>)}</tbody></table></div></Panel>{maintenance && <Panel title="Maintenance log" action={<button onClick={() => setMaintenance(null)}>Close</button>}><Form fields={[{ name: 'description', label: 'Work performed' }, { name: 'cost', label: 'Cost (USD)', type: 'number', min: 0, step: '.01' }, { name: 'odometer', label: 'Odometer', type: 'number', min: 0 }, { name: 'performedAt', label: 'Service date', type: 'date' }]} submit="Record maintenance" onSubmit={async (v) => { await post(`/fleet/${maintenance}/maintenance`, { ...v, cost: Math.round(Number(v.cost) * 100), odometer: Number(v.odometer) }); reload(); toast('Maintenance recorded'); }}/><div className="list">{history?.map(h => <div key={h.id}><strong>{h.description}</strong><span>{h.performed_at} · {h.odometer} km · {money(h.cost)}</span></div>)}</div></Panel>}</>; }
export function Hubs() { const { data, error } = useData<Hub[]>('/hubs'), { data: scans } = useData<{
    id: string;
    tracking: string;
    hub_name: string;
    action: string;
    actor_name: string;
    created_at: string;
}[]>('/hubs/scans'); const { user, reload, toast } = useApp(), [show, setShow] = useState(false); return <><PageTitle title="Hubs & warehouse" subtitle="Record each custody handoff across your network." action={user.role !== 'WAREHOUSE' && <button className="primary" onClick={() => setShow(!show)}><Plus size={16}/> Add hub</button>}/><ErrorBox message={error}/>{show && <Panel title="New hub"><Form fields={[{ name: 'name', label: 'Hub name' }, { name: 'city', label: 'City' }, { name: 'address', label: 'Street address' }, { name: 'capacity', label: 'Parcel capacity', type: 'number', min: 1 }]} submit="Create hub" onSubmit={async (v) => { await post('/hubs', { ...v, capacity: Number(v.capacity) }); setShow(false); reload(); }}/></Panel>}<div className="hub-grid">{data?.map(h => <Panel key={h.id} title={h.name}><span className="eyebrow">{h.city}</span><p>{h.address}</p><div className="occupancy"><strong>{h.occupancy}</strong><span>/ {h.capacity} parcels</span></div><div className="mini-progress"><span style={{ width: h.occupancy / h.capacity * 100 + '%' }}/></div></Panel>)}</div><Panel title="Scan a parcel"><Form fields={[{ name: 'tracking', label: 'Tracking number', placeholder: 'Scan or paste ATL-…' }, { name: 'hubId', label: 'Hub', type: 'select', options: data?.map(h => ({ value: h.id, label: h.name })) }, { name: 'action', label: 'Custody action', type: 'select', options: options(['RECEIVE', 'DEPART']) }]} submit="Record scan" onSubmit={async (v) => { await post('/hubs/scans', v); reload(); toast('Custody scan recorded'); }}/></Panel><Panel title="Recent scans"><div className="table-wrap"><table><thead><tr><th>Tracking</th><th>Hub</th><th>Action</th><th>Operator</th><th>Time</th></tr></thead><tbody>{scans?.map(s => <tr key={s.id}><td className="tracking">{s.tracking}</td><td>{s.hub_name}</td><td><Badge value={s.action}/></td><td>{s.actor_name}</td><td>{date(s.created_at)}</td></tr>)}</tbody></table></div></Panel></>; }
interface RouteRow {
    id: string;
    name: string;
    driver_id: string;
    vehicle_id: string;
    driver_name: string;
    plate: string;
    route_date: string;
    status: string;
    stop_count: number;
}
export function RoutesPage() { const { user, reload, toast } = useApp(); const canEdit = user.role !== 'DRIVER'; const { data, error } = useData<RouteRow[]>('/routes'), { data: drivers } = useData<User[]>(canEdit ? '/users?role=DRIVER' : null), { data: vehicles } = useData<Vehicle[]>(canEdit ? '/fleet' : null), { data: shipments } = useData<{
    items: Shipment[];
}>(canEdit ? '/shipments?limit=100' : null); const [show, setShow] = useState(false), [selected, setSelected] = useState<string | null>(null), [chosen, setChosen] = useState<string[]>([]); const { data: detail } = useData<{
    route: RouteRow;
    stops: (Shipment & {
        position: number;
    })[];
}>(selected ? '/routes/' + selected : null); return <><PageTitle title="Routes & manifests" subtitle="Plan ordered delivery runs for your drivers and vehicles." action={canEdit && <button className="primary" onClick={() => setShow(!show)}><Plus size={16}/> Plan route</button>}/><ErrorBox message={error}/>{show && <Panel title="New delivery run"><Form fields={[{ name: 'name', label: 'Route name' }, { name: 'date', label: 'Run date', type: 'date' }, { name: 'driverId', label: 'Assigned driver', type: 'select', options: drivers?.filter(d => d.active).map(d => ({ value: d.id, label: d.name })) }, { name: 'vehicleId', label: 'Assigned vehicle', type: 'select', options: vehicles?.filter(v => v.status === 'AVAILABLE').map(v => ({ value: v.id, label: v.plate })) }, { name: 'optimize', label: 'Stop ordering', type: 'select', value: 'false', options: [{ value: 'false', label: 'Selection order' }, { value: 'true', label: 'Nearest neighbour (straight-line estimate)' }] }]} submit="Create route" onSubmit={async (v) => { const r = await post<{
    id: string;
}>('/routes', { ...v, optimize: v.optimize === 'true', shipmentIds: chosen }); setSelected(r.id); setShow(false); setChosen([]); reload(); toast('Route planned'); }}><fieldset><legend>Select assigned shipments in delivery order</legend><p className="muted">All selected shipments must share the chosen driver and vehicle. Showing the newest 100 shipments.</p><div className="checkbox-list">{shipments?.items.filter(s => ['ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY'].includes(s.status)).map(s => <label key={s.id}><input type="checkbox" checked={chosen.includes(s.id)} onChange={e => setChosen(e.target.checked ? [...chosen, s.id] : chosen.filter(x => x !== s.id))}/><span>{s.tracking} · {s.delivery_city}<small>{s.driver_name} / {s.plate}{chosen.includes(s.id) && ` · stop ${chosen.indexOf(s.id) + 1}`}</small></span></label>)}</div></fieldset></Form></Panel>}<Panel><div className="table-wrap"><table><thead><tr><th>Route</th><th>Driver / vehicle</th><th>Date</th><th>Stops</th><th>Status</th><th /></tr></thead><tbody>{data?.map(r => <tr key={r.id}><td>{r.name}</td><td>{r.driver_name}<small>{r.plate}</small></td><td>{r.route_date}</td><td>{r.stop_count}</td><td><Badge value={r.status}/></td><td><button onClick={() => setSelected(r.id)}>Open manifest</button></td></tr>)}</tbody></table>{!data?.length && <Empty>No routes planned yet. Assign shipments, then create a delivery run.</Empty>}</div></Panel>{detail && <Panel title={detail.route.name} action={<button onClick={() => window.print()}><Printer size={15}/> Print manifest</button>}><p>{detail.route.route_date} · <Badge value={detail.route.status}/></p><ol className="manifest">{detail.stops.map(s => <li key={s.id}><strong>{s.position}</strong><div><Link to={'/shipments/' + s.id}>{s.tracking}</Link><p>{s.delivery_address} · {s.recipient_name}</p><small>{s.recipient_phone}</small></div><Badge value={s.status}/></li>)}</ol>{detail.route.status !== 'COMPLETED' && <Action className="primary" run={() => post('/routes/' + selected + '/status', { status: detail.route.status === 'PLANNED' ? 'ACTIVE' : 'COMPLETED' })}>{detail.route.status === 'PLANNED' ? 'Start route' : 'Complete route'}</Action>}</Panel>}</>; }
export function Directory({ customers = false }: {
    customers?: boolean;
}) { const { data, error } = useData<User[]>('/users' + (customers ? '?role=CUSTOMER' : '')); const { user, reload, toast } = useApp(); const [show, setShow] = useState(false); return <><PageTitle title={customers ? 'Customer directory' : 'Team & access'} subtitle={customers ? 'Customer accounts connected to your logistics workspace.' : 'Create staff accounts and control access to the platform.'} action={user.role === 'ADMIN' && <button className="primary" onClick={() => setShow(!show)}><Plus size={16}/> Add {customers ? 'customer' : 'team member'}</button>}/><ErrorBox message={error}/>{show && <Panel title="New account"><Form fields={[{ name: 'name', label: 'Full name / company' }, { name: 'email', label: 'Email address', type: 'email' }, { name: 'phone', label: 'Phone' }, { name: 'password', label: 'Initial password (at least 12 characters)', type: 'password' }, { name: 'role', label: 'Role', type: 'select', value: customers ? 'CUSTOMER' : 'DISPATCHER', options: options(customers ? ['CUSTOMER'] : roles) }]} submit="Create account" onSubmit={async (v) => { await post('/users', v); setShow(false); reload(); toast('Account created'); }}/></Panel>}<Panel><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email / phone</th><th>Role</th><th>Status</th><th>Created</th>{user.role === 'ADMIN' && <th />}</tr></thead><tbody>{data?.map(u => <tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}<small>{u.phone}</small></td><td><Badge value={u.role}/></td><td><Badge value={u.active ? 'ACTIVE' : 'INACTIVE'}/></td><td>{date(u.created_at)}</td>{user.role === 'ADMIN' && <td>{u.id !== user.id && <Action confirm={`${u.active ? 'Deactivate' : 'Activate'} ${u.name}?`} run={() => patch('/users/' + u.id, { active: !u.active })}>{u.active ? 'Deactivate' : 'Activate'}</Action>}</td>}</tr>)}</tbody></table></div></Panel></>; }
